
#
# ns_worm_detection_svm_model_generator.r
#
# Nicholas Stroustrup 8/2018
#
# This file demonstrates how build Lifespan Machine worm detection model files 
# using the R programming language bindings to libsvm
#
# The base_analysis_directory variable should be set to the absolute path
# of the analysis files generated by the worm browser (see worm detection model generation instructions)
# model_file_to_analyze sholud then be set to the relative pathname of the model file you want to generate
#
# The worm detection model file is written to the same directory as the input files,
# and some diagnostic data is plotted

library("e1071");
library(rgl)
library("ranger")

base_analysis_directory = "X:\\microscopy\\lifespan_machine\\2019_10=worm_detection_training_set\\analysis"
model_file_to_analyze = "training_sets\\high_24_plus_fscore_features_without_reg_i"
#.5 means equal weighting.  deviations towards 1 reduces false-negative and increases false positives
prefer_false_positives = .75;

setwd(base_analysis_directory);

#Function to load in SVM feature files generated by the lifespan machine
ns_read_svm_format = function (filename,features_filename=""){
	raw = read.table(filename,header=F,sep=' ');
	if (!any(!is.na(raw[,dim(raw)[2]])))
		raw = raw[,1:(dim(raw)[2]-1)]
	feature_values=as.data.frame(apply(raw,c(1,2),function(x) as.numeric(sub(".*:","",x))))
	
	feature_indicies=as.numeric(apply(raw[1,2:(dim(raw)[2])],1,function(x) as.numeric(sub(":.*","",x))))
	
	if (features_filename != ""){
		feature_name_lookup = read.table(features_filename,header=F,sep='\t');
		#browser()
		indx = match(feature_indicies,feature_name_lookup$V1+1) #the plus one is because the lifespan machine source code is offset from 1 compared to the feature numbers sent to libSVM
		features = as.character(feature_name_lookup$V2[indx])
	} else features = unlist(lapply(1:(dim(feature_values)[2]-1),function(x)paste0("f",x)))
	
	names(feature_values) = c("is_a_worm",features)
	return(list(features=feature_values,feature_names=feature_name_lookup));
}

#The package "e1071" disregards feature and label numbers, so we need to reload and correct output files
ns_write_compatible_svm_model = function(model_base_filename,svm.model,feature_names){
	fname = paste0(model_base_filename,"_model_temp.txt");
	fname2 = paste0(model_base_filename,"_model.txt");
	write.svm(svm.model,svm.file=fname);

	fo = unique(feature_names$V1[order(feature_names$V1)])
	line_num = 0;
	 infile = file(fname, "r") 
	 outfile = file(fname2, "w")
	  while ( TRUE ) {
	    line = readLines(infile, n = 1)  
	    if ( length(line) == 0 ) {
	      break
	    }
	    if (line_num == 6){
		writeLines("label 1 -1",outfile); 	
	    }else if (line_num < 9){
		 writeLines(line,outfile);
	    } else{
		splt = strsplit(line," ")
		out = paste0(splt[[1]][1]," ");
		poss = attr(regexpr(".*:",splt[[1]]),"match.length")
		vals = substring(splt[[1]][2:length(poss)],poss[2:length(poss)]+1,1000)
		#browser()
		for (i in 1:length(vals))
			out = paste0(out,fo[i]+1,":",vals[i]," ");
		 writeLines(out,outfile);	
		}
	    line_num = line_num+1

	  }
	  close(infile)
	  close(outfile)
	  file.remove(fname);
}

if (!exists("training_set")){

#load training and test data from disk
ts = ns_read_svm_format(paste0(model_file_to_analyze,"_test.txt"),paste0(model_file_to_analyze,"_included_stats.txt"));
test_set = ts[["features"]];
feature_names = ts[["feature_names"]];
training_set = ns_read_svm_format(paste0(model_file_to_analyze,"_train.txt"),paste0(model_file_to_analyze,"_included_stats.txt"))[["features"]];
}

#use libSVM to build the model
svm.model = svm(is_a_worm ~. , data = training_set,
		kernel="radial", type="C-classification",
		gamma=.7,cost = 20,scale=F,probability=F,class.weights=c("1"=prefer_false_positives,"-1"=1-prefer_false_positives))
svm.pred = predict(svm.model,test_set)
svm.results = table(pred = as.numeric(as.character(svm.pred))>0, true = test_set[,1])
svm.fp = which(as.numeric(as.character(svm.pred))>0 & as.numeric(as.character(test_set$is_a_worm))<0)
svm.fn = which(as.numeric(as.character(svm.pred))<0 & as.numeric(as.character(test_set$is_a_worm))>0)
svm.accuracy = (svm.results [1,1]+svm.results [2,2])/sum(svm.results )
svm.confusion = svm.results/sum(svm.results);
rownames(svm.confusion) = c("Not Worm","Worm");
colnames(svm.confusion) = c("Not Worm","Worm");
print(paste("SVM accuracy:",svm.accuracy))
print("SVM Confusion Matrix:");
print(svm.confusion);

#write the model to disk
ns_write_compatible_svm_model(model_file_to_analyze,svm.model,feature_names);
#write the prediction results file to disk (for additional diagnostics)
write.table(svm.pred,file=paste0(model_file_to_analyze,"_results.txt"),sep=" ",row.names=F,col.names=F,quote=F);

  
#build a random forrest model to identify most useful features
set.seed(71)
training_set$is_a_worm = as.factor(as.character(training_set$is_a_worm ))
rf.model <- ranger(is_a_worm ~ ., data=training_set, importance="impurity",num.trees=1000,respect.unordered.factors="ignore")
rf.pred = predict(rf.model, data=test_set)
rf.results =  table(pred = rf.pred$predictions, true = test_set[,1])
rf.accuracy = (rf.results [1,1]+rf.results [2,2])/sum(rf.results )
rf.confusion = rf.results/sum(rf.results);
rownames(rf.confusion) = c("Not Worm","Worm");
colnames(rf.confusion) = c("Not Worm","Worm");
print(paste("Random Forrest Accuracy:",rf.accuracy))
print("Random Forrest Confusion Matrix:");
print(rf.confusion);
#}

#plot most useful features
par(mar=c(16,2,2,2))
v = order(rf.model$variable.importance,decreasing=T)
vn = names(rf.model$variable.importance)[v]
plot(1:length(v),rf.model$variable.importance[v],xaxt="n",xlab="")
vx = as.numeric(v)
axis(1, at=vx, labels=FALSE)
text(x=vx, y=par()$usr[3]-0.05*(par()$usr[4]-par()$usr[3]),labels=as.character(vn), srt=90, adj=1, xpd=TRUE)
readline(prompt="Press [enter] to continue")
m = cov(test_set[2:(dim(test_set)[2])])
pca_res <- prcomp(m,center = F,scale. = F) 
plot(pca_res,type="l")
title("Variance explained by pca vectors")
readline(prompt="Press [enter] to continue")

#plot worms and non-worms and overlay SVM mistakes
base_size = 2;
d = as.matrix(test_set[,2:(dim(test_set)[2])])
tf = d %*% pca_res$rotation 
cols = c("green","black","red","pink")
col = cols[2-1*(test_set[,"is_a_worm"]>0)]
big = rep(F,length(col))
col[svm.fp] = cols[3]
col[svm.fn] = cols[4]
big[svm.fp] = T
big[svm.fn] = T
plot3d(tf[!big,1],tf[!big,2],tf[!big,3],col=col[!big],size=base_size,xlab="PCV1",ylab="PCV2",zlab="PCV3")
legend3d("topright",legend=c("worms","non-worms"),pch=16,col=cols[1:2], inset=c(0.02))
readline(prompt="Press [enter] to continue")
points3d(tf[big,1],tf[big,2],tf[big,3],col=col[big],size=base_size*4)
#next3d(reuse=F)
legend3d("topright",legend=c("worms","non-worms","SVM false-positive","SVM false-negative"),pch=16,col=cols, inset=c(0.02))